OPS-113: Proto
valitydev/repairer-proto pull request #1
Opened 2022-06-14 16:33 UTC by inallyoung

2022-06-15 15:48 UTC, keynslug commented on proto/repairer.thrift
> +    repaired
Не очень понятна разница между этими статусами, особенно учитывая что в mg статуса repaired нет. Плюс если сервис заведует только упавшими машинами, то не очень понятно, что значит _in progress_.

2022-06-15 15:48 UTC, keynslug commented on proto/repairer.thrift
> +    RepairResponse RepairInvoices (1: RepairInvoicesRequest request);
С точки зрения интеграции фронта мне такой интерфейс кажется неудобным. Если оператор захочет починить 1000 инвойсов, то фронт будет ждать (условно) 100 секунд, прежде чем получит синхронный ответ? Я б тут конечно ввёл понятие батчей со своими идентификаторами и возможностью узнать прогресс выполнения. <sup>В базовой реализации их вообще можно было бы чисто в памяти держать.</sup>

2022-06-16 08:44 UTC, inallyoung commented on proto/repairer.thrift
> +    RepairResponse RepairInvoices (1: RepairInvoicesRequest request);
предполагается, что это будет асинхронный вызов, метод вернет список со статусами **in_progress**, чтобы задизеблить эти машины для фронта, далее фронт будет обновлять страницу пока все не обновятся до **repaired** или снова **failed**

2022-06-16 11:36 UTC, keynslug commented on proto/repairer.thrift
> +    RepairResponse RepairInvoices (1: RepairInvoicesRequest request);
Понял в целом. Не до конца понятно, как интерактивность будет работать.
1. Фронт отправил `RepairInvoices` на 1000 инвойсов.
2. Получил ответ, пометил их всех как in progress. (Тут тогда непонятно, зачем возвращать тот же набор идентификаторов машин обратно в `RepairResponse`, фронт и так их знает по идее)
3. Обновил страницу. (Типа отправил тот же самый запрос `Search`, по которому он нашёл эту 1000 машин? Или обновление здесь на операторе, типа пусть жмёт refresh когда посчитает нужным?)

Машины в статусе _repaired_ кстати будут вечно жить в базе сервиса? Или у них какой-то срок жизни будет ограниченный?

2022-06-16 11:55 UTC, inallyoung commented on proto/repairer.thrift
> +    RepairResponse RepairInvoices (1: RepairInvoicesRequest request);
>Получил ответ, пометил их всех как in progress (Тут тогда непонятно, зачем возвращать тот же набор идентификаторов машин обратно в RepairResponse, фронт и так их знает по идее)

сделал так для единообразия с методом Search, чтобы не было хардкода на стороне фронта. 
И думаю в случае если машин не очень много (например, меньше 10 или если запись одна), то можно синхронно обработать и сразу вернуть результат. 

>Обновил страницу. (Типа отправил тот же самый запрос Search, по которому он нашёл эту 1000 машин? Или обновление здесь на операторе, типа пусть жмёт refresh когда посчитает нужным?)

тут я сам до конца не знаю как лучше. Думаю можно вызывать search, пока не исчезнет последний in_progress.

>Машины в статусе repaired кстати будут вечно жить в базе сервиса? Или у них какой-то срок жизни будет ограниченный?

не думал над этим, по дефолту пусть живет вечно. Это на что-то влияет?

2022-06-16 11:58 UTC, keynslug commented on proto/repairer.thrift
> +    RepairResponse RepairInvoices (1: RepairInvoicesRequest request);
> Это на что-то влияет?

На размер базы и индекса разве что.

2022-06-16 11:59 UTC, keynslug reviewed
Я в целом всё понял, думаю что тут уже @KeinAsylum нужен.

2022-06-16 11:59 UTC, keynslug commented on proto/repairer.thrift
> +    4: required Status status
Я б тогда разве что переименовал бы в
```suggestion
    4: required RepairStatus status
```
Чтобы не было путаницы со статусом машины в mg.

2022-06-16 12:00 UTC, keynslug submitted a review, later dismissed

2022-06-16 16:40 UTC, KrickRay requested changes

2022-06-16 16:40 UTC, KrickRay commented on proto/repairer.thrift
> +    1: optional MachineID id
нам думаю нужно будет сразу запрашивать списком машины, может это list'ом сделать?

2022-06-16 16:41 UTC, KrickRay commented
почему новые протоколы не содержат фронтовую сборку? может гитхаб шаблон создадим, чтобы его держать актуальным?

2022-06-17 11:55 UTC, inallyoung commented
Нужна ваша помощь, сборка не проходит @KrickRay 
Ругается, что fistful-proto зависимость не найдена типа

2022-06-17 12:07 UTC, KrickRay commented
@inallyoung я не вижу откуда ему брать withdrawal_session.thrift

2022-06-17 12:08 UTC, inallyoung commented
https://github.com/valitydev/repairer-proto/pull/1/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R26
@KrickRay тип отсюда

2022-06-17 12:09 UTC, KrickRay commented on proto/repairer.thrift
> +include "withdrawal_session.thrift"
```suggestion
include "proto/withdrawal_session.thrift"
```

@inallyoung вроде так должно же быть

2022-06-17 12:14 UTC, inallyoung commented on proto/repairer.thrift
> +include "withdrawal_session.thrift"
так не будет работать уже джава сборка. Но чекну счас.

2022-06-17 12:19 UTC, inallyoung commented
@KrickRay в итоге размотало обе сборки

2022-06-17 12:21 UTC, inallyoung commented
@KrickRay может конфликтуют трифт-файлы дамзели и фистфула, у которых одинаковые названия? например base.thrift

2022-06-17 12:21 UTC, inallyoung commented
@KrickRay в джава-сборке я обхожу это копирование дамзели в proto/, а фистфула в корень

2022-06-17 12:24 UTC, KrickRay commented
@KrickRay можешь вернуть, я сделаю конфигурируемым что куда класть для фронтовой

2022-06-17 12:25 UTC, KrickRay commented
@inallyoung можно смержить сломанную фронтовую сборку

2022-06-17 12:27 UTC, KrickRay submitted a review, later dismissed

2022-06-17 12:33 UTC, merged